/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    DirSelect: typeof import('./src/components/dir-select.vue')['default']
    EditableField: typeof import('./src/components/editable-field.vue')['default']
    EditableTable: typeof import('./src/components/editable-table.vue')['default']
    ExecuteButton: typeof import('./src/components/execute-button.vue')['default']
    FormEditor: typeof import('./src/components/form-editor.vue')['default']
    FormViewer: typeof import('./src/components/form-viewer.vue')['default']
    FormViewerGroup: typeof import('./src/components/form-viewer-group.vue')['default']
    ProgressBar: typeof import('./src/components/progress-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerminateButton: typeof import('./src/components/terminate-button.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
